/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CommunityDirectoryRouteImport } from './routes/community-directory'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommunityDirectoryRegisterRouteImport } from './routes/community-directory/register'
import { Route as CommunityDirectoryIdRouteImport } from './routes/community-directory/$id'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as CommunityDirectoryIdEditRouteImport } from './routes/community-directory/$id/edit'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityDirectoryRoute = CommunityDirectoryRouteImport.update({
  id: '/community-directory',
  path: '/community-directory',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityDirectoryRegisterRoute =
  CommunityDirectoryRegisterRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => CommunityDirectoryRoute,
  } as any)
const CommunityDirectoryIdRoute = CommunityDirectoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CommunityDirectoryRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const CommunityDirectoryIdEditRoute =
  CommunityDirectoryIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => CommunityDirectoryIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/community-directory': typeof CommunityDirectoryRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/community-directory/$id': typeof CommunityDirectoryIdRouteWithChildren
  '/community-directory/register': typeof CommunityDirectoryRegisterRoute
  '/community-directory/$id/edit': typeof CommunityDirectoryIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/community-directory': typeof CommunityDirectoryRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/community-directory/$id': typeof CommunityDirectoryIdRouteWithChildren
  '/community-directory/register': typeof CommunityDirectoryRegisterRoute
  '/community-directory/$id/edit': typeof CommunityDirectoryIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRoute
  '/community-directory': typeof CommunityDirectoryRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/community-directory/$id': typeof CommunityDirectoryIdRouteWithChildren
  '/community-directory/register': typeof CommunityDirectoryRegisterRoute
  '/community-directory/$id/edit': typeof CommunityDirectoryIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/community-directory'
    | '/login'
    | '/register'
    | '/search'
    | '/dashboard'
    | '/profile'
    | '/community-directory/$id'
    | '/community-directory/register'
    | '/community-directory/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/community-directory'
    | '/login'
    | '/register'
    | '/search'
    | '/dashboard'
    | '/profile'
    | '/community-directory/$id'
    | '/community-directory/register'
    | '/community-directory/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/community-directory'
    | '/login'
    | '/register'
    | '/search'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/community-directory/$id'
    | '/community-directory/register'
    | '/community-directory/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRoute
  CommunityDirectoryRoute: typeof CommunityDirectoryRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-directory': {
      id: '/community-directory'
      path: '/community-directory'
      fullPath: '/community-directory'
      preLoaderRoute: typeof CommunityDirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-directory/register': {
      id: '/community-directory/register'
      path: '/register'
      fullPath: '/community-directory/register'
      preLoaderRoute: typeof CommunityDirectoryRegisterRouteImport
      parentRoute: typeof CommunityDirectoryRoute
    }
    '/community-directory/$id': {
      id: '/community-directory/$id'
      path: '/$id'
      fullPath: '/community-directory/$id'
      preLoaderRoute: typeof CommunityDirectoryIdRouteImport
      parentRoute: typeof CommunityDirectoryRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/community-directory/$id/edit': {
      id: '/community-directory/$id/edit'
      path: '/edit'
      fullPath: '/community-directory/$id/edit'
      preLoaderRoute: typeof CommunityDirectoryIdEditRouteImport
      parentRoute: typeof CommunityDirectoryIdRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface CommunityDirectoryIdRouteChildren {
  CommunityDirectoryIdEditRoute: typeof CommunityDirectoryIdEditRoute
}

const CommunityDirectoryIdRouteChildren: CommunityDirectoryIdRouteChildren = {
  CommunityDirectoryIdEditRoute: CommunityDirectoryIdEditRoute,
}

const CommunityDirectoryIdRouteWithChildren =
  CommunityDirectoryIdRoute._addFileChildren(CommunityDirectoryIdRouteChildren)

interface CommunityDirectoryRouteChildren {
  CommunityDirectoryIdRoute: typeof CommunityDirectoryIdRouteWithChildren
  CommunityDirectoryRegisterRoute: typeof CommunityDirectoryRegisterRoute
}

const CommunityDirectoryRouteChildren: CommunityDirectoryRouteChildren = {
  CommunityDirectoryIdRoute: CommunityDirectoryIdRouteWithChildren,
  CommunityDirectoryRegisterRoute: CommunityDirectoryRegisterRoute,
}

const CommunityDirectoryRouteWithChildren =
  CommunityDirectoryRoute._addFileChildren(CommunityDirectoryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRoute,
  CommunityDirectoryRoute: CommunityDirectoryRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
